### PR TITLE
JVM configuration options through attribute

### PR DESCRIPTION
**Pull request by jmickle**

### CODE REVIEW

**Comment by jmickle** [comment]
@dwradcliffe can you push this in

**Comment by dwradcliffe** [comment]
Sorry I didn't notice this! Looks pretty good, do you mind squashing your commits?

**Comment by jmickle** [comment]
yeah how do you do that again

**Comment by dwradcliffe** [comment]
Here's a pretty good explanation http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by dwradcliffe** [comment]
This should be possible with the latest changes on master. Thanks!

**Pull request closed without merging**
