### PR TITLE
Verify solr process running if PID file exists

### PR DESCRIPTION
**Pull request by eric-tucker**
This addresses #34.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
LGTM

**Comment by eric-tucker** [comment]
Thanks!

Can you follow-up when published to the supermarket?   Thanks in advance.

**Comment by dwradcliffe** [comment]
Yep, working on getting CI fixed and then I'll publish.

**Comment by dwradcliffe** [comment]
https://supermarket.chef.io/cookbooks/solr/versions/0.6.0

**Pull request merged**
