### PR TITLE
Bump solr version and use default port

### PR DESCRIPTION
**Pull request by eric-tucker**

### CODE REVIEW

**Comment by eric-tucker** [comment]
What's the holdup here?  The default solr port is 8983 so the cookbook shouldn't be trying to set a non-default port value.

And we should be on the latest 4.x version.  Don't encourage people to install an old version.

**Comment by mburns** [comment]
This should be 2 separate changes, IMHO, but I agree with both changes. :+1:

**Comment by dwradcliffe** [comment]
:+1: Not sure why this port has been wrong all this time. Must have been leftover from custom usage.

**Comment by eric-tucker** [comment]
Thanks!  Is this published to the Chef supermarket?

**Comment by dwradcliffe** [comment]
@eric-tucker Just released 0.5.0 :rocket:

**Pull request merged**
